'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const d2n=s=>{const[a,b,c]=s.split('-').map(Number);return Math.round(Date.UTC(a,b-1,c)/864e5)};
const n2d=n=>new Date(n*864e5).toISOString().slice(0,10);
const p2=n=>String(n).padStart(2,'0');
const today=()=>{const d=new Date();return d.getFullYear()+'-'+p2(d.getMonth()+1)+'-'+p2(d.getDate())};
const MES=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
const formatDate=(s,sh)=>{const[y,m,d]=s.split('-').map(Number);return d+' de '+MES[m-1]+(sh?'':' de '+y)};
const dm=s=>p2(+s.slice(8))+'/'+s.slice(5,7);
const validDate=s=>/^\d{4}-\d\d-\d\d$/.test(s||'')&&n2d(d2n(s))===s;
const plural=(n,a,b)=>n+' '+(Math.abs(n)===1?a:b);
const Q=[['normal','♥','Normal'],['bem','😊','Bem'],['cansada','😴','Cansada'],['colicas','😣','Cólicas'],['triste','😔','Triste'],['cabeca','🤕','Dor de cabeça'],['irritada','😡','Irritada'],['inchaco','💧','Inchaço']];
const MOOD=['Feliz','Normal','Triste','Irritada','Ansiosa','Sensível'],SYM=['Cólicas','Dor de cabeça','Dor lombar','Acne','Inchaço','Cansaço','Sensibilidade mamária','Náuseas'],FLOW=['Ligeiro','Moderado','Intenso'];
const MSG=['Hoje é um bom dia para cuidar de ti. ♥','Não te esqueças de descansar.','Escuta o teu corpo.','Cuida de ti com carinho.','Bebe água e respira fundo.','Um passo de cada vez.'];
/* ===== base de dados (IndexedDB) ===== */
let db;
const openDB=()=>new Promise((res,rej)=>{const r=indexedDB.open('fanny-app',1);r.onupgradeneeded=()=>{const d=r.result;d.createObjectStore('profile',{keyPath:'id'});d.createObjectStore('cycles',{keyPath:'id',autoIncrement:true});d.createObjectStore('logs',{keyPath:'date'});d.createObjectStore('settings',{keyPath:'k'})};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)});
const tx=(s,m,f)=>new Promise((res,rej)=>{const t=db.transaction(s,m),o=f(t.objectStore(s));t.oncomplete=()=>res(o&&o.result);t.onerror=()=>rej(t.error)});
const dbAll=s=>tx(s,'readonly',o=>o.getAll()),dbPut=(s,v)=>tx(s,'readwrite',o=>o.put(v)),dbDel=(s,k)=>tx(s,'readwrite',o=>o.delete(k)),dbClr=s=>tx(s,'readwrite',o=>o.clear());
let S={profile:null,cycles:[],logs:{},cfg:{}};
async function load(){const p=await dbAll('profile');S.profile=p[0]||null;S.cycles=(await dbAll('cycles')).sort((a,b)=>d2n(a.start)-d2n(b.start));S.logs={};(await dbAll('logs')).forEach(l=>S.logs[l.date]=l);const c=(await dbAll('settings')).find(x=>x.k==='cfg');S.cfg=c?c.v:{}}
const saveCfg=()=>dbPut('settings',{k:'cfg',v:S.cfg});
/* ===== cálculos ===== */
function calculateCycleLength(i){const c=S.cycles;return i<c.length-1?d2n(c[i+1].start)-d2n(c[i].start):null}
const cycleLens=()=>S.cycles.map((_,i)=>calculateCycleLength(i)).filter(x=>x!==null);
function calculateAverageCycle(){const l=cycleLens().filter(x=>x>=15&&x<=60).slice(-6);return l.length?Math.round(l.reduce((a,b)=>a+b)/l.length):S.profile.cycleLen}
function calculatePeriodDuration(c){return c.end?d2n(c.end)-d2n(c.start)+1:null}
function avgPeriod(){const l=S.cycles.map(calculatePeriodDuration).filter(Boolean);return l.length?Math.round(l.reduce((a,b)=>a+b)/l.length):S.profile.periodLen}
const lastC=()=>S.cycles[S.cycles.length-1];
const calculateNextPeriod=()=>n2d(d2n(lastC().start)+calculateAverageCycle());
const daysUntilPeriod=()=>d2n(calculateNextPeriod())-d2n(today());
function calculatePredictionConfidence(){const l=cycleLens();if(l.length<2)return'low';const m=l.reduce((a,b)=>a+b)/l.length;return Math.sqrt(l.reduce((a,b)=>a+(b-m)**2,0)/l.length)>5?'approx':'ok'}
function calculateCyclePhase(){const c=lastC();if(!c)return null;const day=d2n(today())-d2n(c.start),cl=calculateAverageCycle(),pl=avgPeriod(),ov=cl-14;let n=day<pl?'Menstruação':day<ov-1?'Fase folicular':day<=ov+1?'Ovulação (estimativa)':day<cl?'Fase lútea':'Ciclo mais longo que o previsto';return{day,cl,pl,ov,n}}
/* ===== segurança PIN / biometria ===== */
async function hash(s){const salt=S.cfg.salt||(S.cfg.salt=Math.random().toString(36).slice(2)+Date.now());if(window.crypto&&crypto.subtle){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(salt+s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}let h=5381;for(const ch of salt+s)h=(h*33^ch.charCodeAt(0))>>>0;return'f'+h}
const b64=u=>btoa(String.fromCharCode(...new Uint8Array(u)));
async function bioReg(){try{const r=await navigator.credentials.create({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),rp:{name:'Fanny App'},user:{id:crypto.getRandomValues(new Uint8Array(16)),name:'fanny',displayName:'Fanny'},pubKeyCredParams:[{type:'public-key',alg:-7},{type:'public-key',alg:-257}],authenticatorSelection:{authenticatorAttachment:'platform',userVerification:'required'},timeout:60000}});S.cfg.bio=b64(r.rawId);await saveCfg();return true}catch(e){return false}}
async function bioAuth(){try{await navigator.credentials.get({publicKey:{challenge:crypto.getRandomValues(new Uint8Array(32)),allowCredentials:[{type:'public-key',id:Uint8Array.from(atob(S.cfg.bio),c=>c.charCodeAt(0))}],userVerification:'required',timeout:60000}});return true}catch(e){return false}}
/* ===== UI base ===== */
let V='home',cm=(()=>{const d=new Date();return{y:d.getFullYear(),m:d.getMonth()}})();
const NAVOF={hist:'more',phases:'more',learn:'more',help:'more',sett:'more'};
const toast=m=>{const t=$('#toast');t.textContent=m;t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,2800)};
const sheet=h=>{$('#pn').innerHTML=h;$('#sh').hidden=false};
const closeSheet=()=>$('#sh').hidden=true;
function theme(){const t=localStorage.getItem('ff-theme')||'auto';document.documentElement.dataset.t=t;const m=document.querySelector('meta[name=theme-color]');if(m)m.content=t==='dark'?'#17111a':'#7a2b45'}
function render(){const m={home,cal,diary,stats,more,hist,phases,learn,help,sett};$('#main').innerHTML='<div class="pg">'+m[V]()+'</div>';$$('.nv button').forEach(b=>b.classList.toggle('on',b.dataset.v===(NAVOF[V]||V)));window.scrollTo(0,0)}
const back=()=>'<div class="top" style="margin-bottom:14px"><button data-a="go" data-v="more" aria-label="Voltar">‹</button></div>';
const chips=(g,arr,sel,single)=>'<div class="chips">'+arr.map(x=>`<button type="button" class="chip${(single?sel===x:(sel||[]).includes(x))?' on':''}" data-a="chip" data-g="${g}" data-s="${single?1:0}">${esc(x)}</button>`).join('')+'</div>';
/* ===== páginas ===== */
function home(){const p=S.profile,c=lastC(),nx=calculateNextPeriod(),du=daysUntilPeriod(),cf=calculatePredictionConfidence(),ph=calculateCyclePhase(),tl=S.logs[today()]||{},dsc=S.cfg.discreet;
const h=new Date().getHours(),sd=h<12?'Bom dia':h<19?'Boa tarde':'Boa noite';
const pct=Math.min(1,Math.max(0,ph.day/ph.cl)),C=2*Math.PI*44;
const big=du>0?'Daqui a '+plural(du,'dia','dias'):du===0?'Prevista para hoje':'Atraso de '+plural(-du,'dia','dias');
let rem='';const r=S.cfg.rem||{};
if(r.start&&du<=0&&!dsc)rem+='<div class="card">🌸 Já começou? Regista o início da tua menstruação.</div>';
if(r.before&&du>0&&du<=(r.days||2)&&!dsc)rem+=`<div class="card">🌸 ${esc(p.name)}, a tua menstruação está prevista para daqui a ${plural(du,'dia','dias')}.</div>`;
if(r.sym&&!S.logs[today()])rem+='<div class="card">💭 Ainda não registaste como te sentes hoje.</div>';
return `<div class="top"><div><h1>Olá, ${esc(p.name)} ♥</h1><div class="mu">${sd}. Cuida de ti hoje.</div></div><button data-a="go" data-v="sett" aria-label="Definições">⚙</button></div>
${rem}<div class="card hero"><div style="flex:1"><div class="sn mu">PRÓXIMA MENSTRUAÇÃO</div><div class="big ${dsc?'bl':''}" data-a="reveal">${big}</div><div class="sn ${dsc?'bl':''}" data-a="reveal">Previsão: ${formatDate(nx,1)}</div><div class="mu" style="margin-top:6px">${cf==='low'?'Estamos a aprender o teu ciclo. A previsão pode variar.':cf==='approx'?'Previsão aproximada — os teus ciclos têm sido irregulares.':'Menstruação prevista para esta data (pode variar).'}</div></div>
<svg class="ring" viewBox="0 0 104 104"><circle cx="52" cy="52" r="44" stroke="rgba(255,255,255,.25)"/><circle cx="52" cy="52" r="44" stroke="#fff" stroke-dasharray="${C}" stroke-dashoffset="${C*(1-pct)}" transform="rotate(-90 52 52)" style="transition:stroke-dashoffset 1.2s ease"/><text x="52" y="50" text-anchor="middle" fill="#fff" font-size="22" font-family="Georgia">${dsc?'•':ph.day+1}</text><text x="52" y="66" text-anchor="middle" fill="#fff" font-size="10" font-family="system-ui">dia do ciclo</text></svg></div>
<div class="row"><div class="card st"><span class="mu">Duração do período</span><b>${plural(avgPeriod(),'dia','dias')}</b></div><div class="card st"><span class="mu">Ciclo habitual</span><b>${plural(calculateCycleLength.avg=calculateAverageCycle(),'dia','dias')}</b></div></div>
<div class="card"><span class="mu">${dsc?'Fase do ciclo oculta':'Fase atual (estimativa)'}</span><h3>${dsc?'•••':ph.n}</h3><div class="note">${MSG[new Date().getDate()%MSG.length]}</div></div>
<button class="btn" data-a="startP">🩸 Minha menstruação começou</button>
<h2>Como te sentes hoje?</h2><div class="chips q">${Q.map(x=>`<button class="chip${(tl.q||[]).includes(x[0])?' on':''}" data-a="quick" data-k="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}</div>
<button class="btn s" data-a="day" data-d="${today()}">+ Registar hoje</button>
<div class="note">Previsões menstruais não são um método contraceptivo.</div>`}
function cal(){const{y,m}=cm,first=new Date(Date.UTC(y,m,1)),off=(first.getUTCDay()+6)%7,nd=new Date(Date.UTC(y,m+1,0)).getUTCDate(),pl=avgPeriod(),P=new Set(),F=new Set();
S.cycles.forEach(c=>{const s=d2n(c.start),e=c.end?d2n(c.end):s+pl-1;for(let i=s;i<=e;i++)P.add(i)});
if(lastC()){const cl=calculateAverageCycle(),s0=d2n(lastC().start);for(let k=1;k<=4;k++)for(let i=0;i<pl;i++){const n=s0+cl*k+i;if(!P.has(n))F.add(n)}}
let cells=['S','T','Q','Q','S','S','D'].map(x=>`<div class="h">${x}</div>`).join('')+'<span></span>'.repeat(off);
for(let d=1;d<=nd;d++){const ds=y+'-'+p2(m+1)+'-'+p2(d),n=d2n(ds);cells+=`<button data-a="day" data-d="${ds}" class="${P.has(n)?'p ':F.has(n)?'f ':''}${ds===today()?'t ':''}${S.logs[ds]?'l':''}">${d}</button>`}
return `<h1>Calendário</h1><div class="card"><div class="top" style="margin-bottom:12px"><button data-a="cm" data-n="-1">‹</button><h3>${MES[m]} ${y}</h3><button data-a="cm" data-n="1">›</button></div><div class="cal">${cells}</div>
<div class="lg"><span><i style="background:var(--ac)"></i>Menstruação</span><span><i style="background:var(--ac2);border:1.5px dashed var(--ac)"></i>Previsão</span><span><i style="outline:2px solid var(--wn)"></i>Hoje</span><span><i style="background:var(--wn);border-radius:50%"></i>Sintomas registados</span></div></div>
<button class="btn" data-a="startP">🩸 Minha menstruação começou</button><div class="note">Toca num dia para registar. As previsões são estimativas.</div>`}
function diary(){const ks=Object.keys(S.logs).sort().reverse();return `<h1>Diário</h1><button class="btn" data-a="day" data-d="${today()}">+ Registar hoje</button>`+(ks.length?ks.map(k=>{const l=S.logs[k],t=[...(l.q||[]).map(x=>Q.find(q=>q[0]===x)[2]),l.mood,l.flow&&'Fluxo '+l.flow.toLowerCase(),...(l.symptoms||[])].filter(Boolean);return `<button class="li card" data-a="day" data-d="${k}" style="border-radius:22px;display:block"><b>${formatDate(k)}</b><div class="mu">${esc(t.join(' · ')||'Sem sintomas')}${l.pain?' · Dor '+l.pain+'/10':''}</div>${l.notes?`<div class="mu">“${esc(l.notes)}”</div>`:''}</button>`}).join(''):'<div class="card"><h3>Ainda sem registos</h3><p class="mu">Regista como te sentes para começares o teu diário.</p></div>')}
function stats(){const L=cycleLens(),pd=S.cycles.map(calculatePeriodDuration).filter(Boolean),av=a=>a.length?(a.reduce((x,y)=>x+y)/a.length).toFixed(1).replace('.0',''):'—';
if(!S.cycles.length)return '<h1>Estatísticas</h1>'+emptyC();
const mx=Math.max(...L,1),bars=L.slice(-8).map((v,i)=>`<div class="mu">${plural(v,'dia','dias')}</div><div class="bar" style="width:${Math.round(v/mx*100)}%"></div>`).join('');
const box=(l,v)=>`<div class="card st"><span class="mu">${l}</span><b>${v}</b></div>`;
return `<h1>Estatísticas</h1><div class="row">${box('Média do ciclo',av(L)+(L.length?' d':''))}${box('Média da menstruação',av(pd)+(pd.length?' d':''))}</div><div class="row">${box('Ciclo mais curto',L.length?Math.min(...L)+' d':'—')}${box('Ciclo mais longo',L.length?Math.max(...L)+' d':'—')}</div><div class="row">${box('Último ciclo',L.length?L[L.length-1]+' d':'—')}${box('Ciclos registados',S.cycles.length)}</div>
<h2>Duração dos ciclos</h2><div class="card">${L.length?bars:'<p class="mu">Regista pelo menos duas menstruações para ver os gráficos.</p>'}</div>`}
const emptyC=()=>'<div class="card"><h3>Os teus ciclos aparecerão aqui.</h3><p class="mu">Quando a tua próxima menstruação começar, regista aqui para começarmos a construir o teu histórico.</p></div>';
function more(){const it=[['hist','🗂','Histórico'],['phases','🌙','Fases do ciclo'],['learn','📖','Aprende'],['help','🩺','Quando procurar ajuda'],['sett','⚙','Definições']];return `<h1>Mais</h1><div class="card">${it.map(x=>`<button class="li" data-a="go" data-v="${x[0]}"><span>${x[1]} ${x[2]}</span><span>›</span></button>`).join('')}</div><div class="note">Este aplicativo serve para acompanhamento e organização pessoal e não substitui avaliação médica.</div>`}
function hist(){const n=S.cycles.length;return back()+'<h1>Histórico</h1>'+(n?S.cycles.map((c,i)=>{const L=calculateCycleLength(i),d=calculatePeriodDuration(c);return `<button class="li card" data-a="editC" data-id="${c.id}" style="border-radius:22px;display:block"><b>Ciclo #${i+1}</b><div>${dm(c.start)} → ${c.end?dm(c.end):'em curso'}</div><div class="mu">${d?plural(d,'dia','dias'):'Duração por registar'} · Ciclo: ${L?plural(L,'dia','dias'):'em curso'}</div></button>`}).reverse().join(''):emptyC())+'<button class="btn" data-a="startP">+ Registar menstruação</button>'}
function phases(){const ph=calculateCyclePhase(),pl=ph.pl,ov=ph.ov,cl=ph.cl,L=[['Menstruação','1–'+pl,'O revestimento do útero é eliminado.'],['Fase folicular',(pl+1)+'–'+(ov-2),'O corpo prepara um novo óvulo.'],['Ovulação (estimativa)',(ov-1)+'–'+(ov+1),'Pode variar muito de ciclo para ciclo.'],['Fase lútea',(ov+2)+'–'+cl,'O corpo prepara-se para o próximo ciclo.']];return back()+'<h1>Fases do ciclo</h1><p class="mu">Estimativas baseadas nos teus dados. Pode variar.</p>'+L.map(x=>`<div class="card" ${ph.n.startsWith(x[0].split(' ')[0])?'style="outline:2px solid var(--ac)"':''}><h3>${x[0]}</h3><div class="mu">Dias ${x[1]} do ciclo</div><p>${x[2]}</p></div>`).join('')+'<div class="note">Esta previsão não deve ser usada como método contraceptivo. Nunca é certeza.</div>'}
function learn(){const T=[['O que é o ciclo menstrual?','É a sequência de mudanças que o corpo faz todos os meses. Conta-se do primeiro dia de uma menstruação até ao dia anterior à seguinte.'],['Por que a menstruação acontece?','Quando não há gravidez, o revestimento do útero é eliminado, o que causa o sangramento.'],['O que pode causar cólicas?','Contrações do útero durante a menstruação. Calor local, descanso e movimento suave costumam aliviar. Se a dor for forte, fala com um profissional de saúde.'],['Como cuidar de ti durante a menstruação?','Descansa quando precisas, bebe água, alimenta-te bem e escolhe o que te faz sentir confortável.'],['Quando procurar ajuda médica?','Consulta a área “Quando procurar ajuda” para ver os sinais de alerta.'],['Por que o ciclo pode variar?','Stress, sono, alimentação, mudanças de rotina e fases da vida podem alterar a duração do ciclo.'],['Menstruação irregular','Ciclos com durações muito diferentes entre si são considerados irregulares. Regista os teus ciclos e fala com um profissional se houver dúvidas.']];return back()+'<h1>Aprende</h1><div class="card">'+T.map(t=>`<details><summary>${t[0]}</summary><p class="mu">${t[1]}</p></details>`).join('')+'</div><div class="note">Este aplicativo serve para acompanhamento e organização pessoal e não substitui avaliação médica.</div>'}
function help(){return back()+'<h1>Quando procurar ajuda</h1><div class="card"><p>Procura um profissional de saúde se tiveres:</p><ul><li>sangramento muito intenso</li><li>dor muito forte ou incapacitante</li><li>desmaio</li><li>sintomas que te preocupam</li><li>alterações menstruais persistentes</li><li>ausência prolongada da menstruação, quando houver possibilidade de gravidez</li></ul><p class="mu">Esta lista não faz diagnósticos. Na dúvida, procura sempre ajuda.</p></div>'}
function sett(){const p=S.profile,c=S.cfg,r=c.rem||{},t=localStorage.getItem('ff-theme')||'auto',lc=lastC();
const sw=(k,l,v)=>`<label style="display:flex;justify-content:space-between;align-items:center;margin:8px 0"><span style="font-weight:400">${l}</span><input type="checkbox" data-c="${k}" ${v?'checked':''} style="width:26px;min-height:26px"></label>`;
return back()+`<h1>Definições</h1><h2>Perfil</h2><div class="card"><label>Nome</label><input id="sn" value="${esc(p.name)}"><label>Idade</label><input id="sa" type="number" inputmode="numeric" value="${esc(p.age)}"><label>Cidade</label><input id="sc" value="${esc(p.city)}"><div id="e1" class="err"></div><button class="btn s" data-a="saveP">Guardar perfil</button></div>
<h2>Ciclo</h2><div class="card"><label>Última menstruação</label><input id="sl" type="date" max="${today()}" value="${lc?lc.start:''}"><label>Duração da menstruação (dias)</label><input id="sp" type="number" inputmode="numeric" value="${p.periodLen}"><label>Duração habitual do ciclo (dias)</label><input id="scl" type="number" inputmode="numeric" value="${p.cycleLen}"><div class="note">Com vários ciclos registados, a média real é usada nas previsões.</div><div id="e2" class="err"></div><button class="btn s" data-a="saveC">Guardar ciclo</button></div>
<h2>Notificações</h2><div class="card">${sw('rem.before','Lembrete antes da menstruação',r.before)}${sw('rem.start','Lembrete para registar o início',r.start)}${sw('rem.sym','Lembrete para registar sintomas',r.sym)}<label>Avisar</label><select data-c="rem.days">${[1,2,3,5].map(d=>`<option value="${d}" ${(r.days||2)===d?'selected':''}>${d} dia${d>1?'s':''} antes</option>`).join('')}</select><div class="note">${'Notification' in window?'Notificações locais funcionam com a app aberta ou instalada. Podem não chegar com a app fechada em alguns telemóveis; os avisos aparecem sempre dentro da app.':'Este navegador não suporta notificações. Os avisos aparecem dentro da app.'}</div></div>
<h2>Aparência</h2><div class="card"><select data-c="theme"><option value="auto" ${t==='auto'?'selected':''}>Automático</option><option value="light" ${t==='light'?'selected':''}>Claro</option><option value="dark" ${t==='dark'?'selected':''}>Escuro</option></select></div>
<h2>Privacidade</h2><div class="card">${sw('discreet','Modo discreto',c.discreet)}${sw('hideName','Esconder o nome da app nas notificações',c.hideName)}<button class="btn s" data-a="pin">${c.pin?'Alterar ou desativar PIN':'Ativar PIN'}</button>${c.pin?`<button class="btn s" data-a="bioreg">${c.bio?'Biometria ativa — reconfigurar':'Usar biometria'}</button>`:''}</div>
<h2>Dados</h2><div class="card"><button class="btn s" data-a="export">Exportar meus dados</button><button class="btn s" data-a="import">Importar meus dados</button><input type="file" id="fi" accept="application/json,.json" hidden><button class="btn d" data-a="wipe">Apagar todos os dados</button></div>
<h2>Sobre</h2><div class="card"><b>Fanny App</b> · versão 1.0<p class="mu">Cuida de ti, ciclo após ciclo. Os teus dados ficam só neste dispositivo e a app funciona sem Internet.</p></div>`}
/* ===== painéis ===== */
function startP(){sheet(`<h2 style="margin-top:0">Quando começou?</h2><input id="ps" type="date" max="${today()}" value="${today()}"><label>Quando terminou? (opcional)</label><input id="pe" type="date" max="${today()}"><div id="pr" class="err"></div><button class="btn" data-a="saveStart">Guardar</button><button class="btn s" data-a="close">Cancelar</button>`)}
function validateCycle(s,e,id){if(!validDate(s))return'Por favor, indica a data em que começou a tua menstruação.';if(d2n(s)>d2n(today()))return'A data de início não pode estar no futuro.';if(e){if(!validDate(e))return'A data de fim não é válida.';if(d2n(e)<d2n(s))return'A data de fim não pode ser anterior ao início.';if(d2n(e)-d2n(s)>14)return'A menstruação não pode durar mais de 15 dias.'}
if(S.cycles.some(c=>c.id!==id&&Math.abs(d2n(c.start)-d2n(s))<10))return'Já existe um registo muito próximo desta data.';
if(e&&S.cycles.some(c=>c.id!==id&&d2n(c.start)>d2n(s)&&d2n(c.start)<=d2n(e)))return'O fim não pode ultrapassar o início do ciclo seguinte.';return''}
async function saveCycle(s,e,id){const er=validateCycle(s,e,id);if(er)return er;const o={start:s,end:e||null,createdAt:Date.now()};if(id){const old=S.cycles.find(c=>c.id===id);o.id=id;o.createdAt=old.createdAt;o.notes=old.notes}await dbPut('cycles',o);await load();return''}
function dayS(d){const l=S.logs[d]||{};sheet(`<h2 style="margin-top:0">${formatDate(d)}</h2><div class="row"><button class="btn s" data-a="pStart" data-d="${d}">🩸 Começou</button><button class="btn s" data-a="pEnd" data-d="${d}">Terminou</button></div><label>Humor</label>${chips('mood',MOOD,l.mood,1)}<label>Sintomas</label>${chips('sym',SYM,l.symptoms)}<label>Fluxo</label>${chips('flow',FLOW,l.flow,1)}<label>Dor: <span id="pv">${l.pain||0}</span>/10</label><input id="pain" type="range" min="0" max="10" value="${l.pain||0}" oninput="pv.textContent=this.value"><label>Observações</label><textarea id="nt" maxlength="500">${esc(l.notes||'')}</textarea><input type="hidden" id="dd" value="${d}"><button class="btn" data-a="saveDay">Guardar</button>${S.logs[d]?'<button class="btn s" data-a="delDay" data-d="'+d+'">Apagar registo do dia</button>':''}`)}
function editC(id){const c=S.cycles.find(x=>x.id===id);sheet(`<h2 style="margin-top:0">Editar menstruação</h2><label>Início</label><input id="ps" type="date" max="${today()}" value="${c.start}"><label>Fim</label><input id="pe" type="date" max="${today()}" value="${c.end||''}"><div id="pr" class="err"></div><button class="btn" data-a="saveEdit" data-id="${id}">Guardar</button><button class="btn d" data-a="delC" data-id="${id}">Apagar</button>`)}
const msgOK=m=>{closeSheet();render();toast(m)};
/* ===== ações ===== */
const A={
go:e=>{V=e.dataset.v;render()},close:closeSheet,reveal:e=>{if(S.cfg.discreet)$$('.bl').forEach(x=>x.classList.remove('bl'))},
cm:e=>{cm.m+=+e.dataset.n;if(cm.m<0){cm.m=11;cm.y--}if(cm.m>11){cm.m=0;cm.y++}render()},
chip:e=>{if(e.dataset.s==='1'){const was=e.classList.contains('on');$$('[data-g="'+e.dataset.g+'"]').forEach(x=>x.classList.remove('on'));if(!was)e.classList.add('on')}else e.classList.toggle('on')},
startP,day:e=>dayS(e.dataset.d),editC:e=>editC(+e.dataset.id),
async quick(e){const d=today(),l=S.logs[d]||{date:d};l.q=l.q||[];const k=e.dataset.k;l.q=l.q.includes(k)?l.q.filter(x=>x!==k):[...l.q,k];await dbPut('logs',l);await load();render()},
async saveStart(){const s=$('#ps').value,e=$('#pe').value,er=await saveCycle(s,e);if(er)return $('#pr').textContent=er;msgOK('Menstruação registada ♥')},
async saveEdit(el){const er=await saveCycle($('#ps').value,$('#pe').value,+el.dataset.id);if(er)return $('#pr').textContent=er;msgOK('Alterações guardadas ♥')},
async delC(el){if(S.cycles.length<2)return $('#pr').textContent='Tens de manter pelo menos um ciclo registado.';await dbDel('cycles',+el.dataset.id);await load();msgOK('Registo apagado')},
async pStart(el){const er=await saveCycle(el.dataset.d,null);if(er)return toast(er);msgOK('Menstruação registada ♥')},
async pEnd(el){const d=el.dataset.d,c=[...S.cycles].reverse().find(x=>d2n(x.start)<=d2n(d));if(!c)return toast('Regista primeiro o início da menstruação.');const er=await saveCycle(c.start,d,c.id);if(er)return toast(er);msgOK('Fim registado ♥')},
async saveDay(){const d=$('#dd').value,g=k=>$$('[data-g="'+k+'"].on').map(x=>x.textContent),o=S.logs[d]||{date:d};Object.assign(o,{date:d,mood:g('mood')[0]||'',symptoms:g('sym'),flow:g('flow')[0]||'',pain:+$('#pain').value,notes:$('#nt').value.trim().slice(0,500)});await dbPut('logs',o);await load();msgOK('Registo guardado ♥')},
async delDay(el){await dbDel('logs',el.dataset.d);await load();msgOK('Registo apagado')},
async saveP(){const n=$('#sn').value.trim(),a=+$('#sa').value,c=$('#sc').value.trim();if(!n||!c||!Number.isInteger(a)||a<8||a>99)return $('#e1').textContent='Preenche nome, idade (8–99) e cidade.';Object.assign(S.profile,{name:n.slice(0,40),age:a,city:c.slice(0,60)});await dbPut('profile',S.profile);toast('Perfil guardado ♥')},
async saveC(){const pl=+$('#sp').value,cl=+$('#scl').value,l=$('#sl').value;if(!Number.isInteger(pl)||pl<1||pl>15||!Number.isInteger(cl)||cl<15||cl>60)return $('#e2').textContent='Menstruação: 1–15 dias. Ciclo: 15–60 dias.';if(!validDate(l))return $('#e2').textContent='Por favor, indica a data em que começou a tua última menstruação.';
const c=lastC();if(c.start!==l){const er=await saveCycle(l,c.end&&d2n(c.end)>=d2n(l)?c.end:null,c.id);if(er)return $('#e2').textContent=er}
Object.assign(S.profile,{periodLen:pl,cycleLen:cl,unknown:false});await dbPut('profile',S.profile);await load();toast('Ciclo atualizado ♥');render()},
pin(){const h=!!S.cfg.pin;sheet(`<h2 style="margin-top:0">${h?'Alterar ou desativar PIN':'Criar PIN'}</h2><label>Novo PIN (4 a 8 números)</label><input id="p1" type="password" inputmode="numeric" maxlength="8"><label>Confirmar PIN</label><input id="p2" type="password" inputmode="numeric" maxlength="8"><div id="pr" class="err"></div><button class="btn" data-a="savePin">Guardar PIN</button>${h?'<button class="btn d" data-a="offPin">Desativar PIN</button>':''}`)},
async savePin(){const a=$('#p1').value,b=$('#p2').value;if(!/^\d{4,8}$/.test(a))return $('#pr').textContent='O PIN deve ter 4 a 8 números.';if(a!==b)return $('#pr').textContent='Os PINs não coincidem.';S.cfg.pin=await hash(a);await saveCfg();msgOK('PIN ativado ♥');render()},
async offPin(){delete S.cfg.pin;delete S.cfg.bio;await saveCfg();msgOK('PIN desativado');render()},
async bioreg(){if(!window.PublicKeyCredential)return toast('Biometria não suportada neste navegador.');toast(await bioReg()?'Biometria ativada ♥':'Não foi possível ativar a biometria.');render()},
async unlock(){if(await hash($('#lpin').value)===S.cfg.pin){$('#lock').hidden=true;$('#lpin').value='';enter()}else $('#lerr').textContent='PIN incorreto.'},
async bioauth(){if(await bioAuth()){$('#lock').hidden=true;enter()}else $('#lerr').textContent='Biometria não confirmada.'},
export(){const o={app:'fanny-app',version:1,exported:new Date().toISOString(),profile:S.profile,cycles:S.cycles,logs:Object.values(S.logs),cfg:{...S.cfg,pin:undefined,bio:undefined,salt:undefined}};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(o,null,1)],{type:'application/json'}));a.download='fanny-app-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),4000);toast('Ficheiro exportado ♥')},
import(){$('#fi').click()},
wipe(){sheet('<h2 style="margin-top:0">Tem certeza?</h2><p>Esta ação não pode ser desfeita.</p><button class="btn d" data-a="wipeOK">Sim, apagar tudo</button><button class="btn s" data-a="close">Cancelar</button>')},
async wipeOK(){for(const s of['profile','cycles','logs','settings'])await dbClr(s);localStorage.clear();location.reload()},
async finish(){enter()}
};
document.addEventListener('click',e=>{const t=e.target.closest('[data-a]');if(t&&A[t.dataset.a])A[t.dataset.a](t)});
document.addEventListener('change',async e=>{const t=e.target;if(t.id==='fi'){importFile(t.files[0]);t.value='';return}const k=t.dataset.c;if(!k)return;
if(k==='theme'){localStorage.setItem('ff-theme',t.value);theme();return}
const v=t.type==='checkbox'?t.checked:+t.value;if(k.startsWith('rem.')){S.cfg.rem=S.cfg.rem||{};S.cfg.rem[k.slice(4)]=v;if(v===true&&'Notification' in window&&Notification.permission==='default')Notification.requestPermission()}else S.cfg[k]=v;await saveCfg();toast('Guardado ♥')});
async function importFile(f){if(!f)return;try{const o=JSON.parse(await f.text());if(o.app!=='fanny-app'||!o.profile||!Array.isArray(o.cycles)||!Array.isArray(o.logs))throw 0;const p=o.profile;if(!p.name||!(p.cycleLen>=15&&p.cycleLen<=60)||!(p.periodLen>=1&&p.periodLen<=15)||!o.cycles.length)throw 0;if(o.cycles.some(c=>!validDate(c.start)||(c.end&&!validDate(c.end)))||o.logs.some(l=>!validDate(l.date)))throw 0;
const keep={pin:S.cfg.pin,bio:S.cfg.bio,salt:S.cfg.salt};for(const s of['profile','cycles','logs'])await dbClr(s);p.id=1;await dbPut('profile',p);for(const c of o.cycles)await dbPut('cycles',{...c,id:undefined,...(c.id?{id:c.id}:{})}).catch(()=>0);for(const l of o.logs)await dbPut('logs',l);S.cfg={...(o.cfg||{}),...keep};await saveCfg();await load();render();toast('Dados importados ♥')}catch(e){toast('Ficheiro inválido. Nada foi alterado.')}}
/* ===== arranque e cadastro ===== */
function onb(step){const o=$('#ob');o.hidden=false;o.innerHTML='<div class="pg">'+(step===1?`<h1 style="margin-top:30px">Vamos conhecer-te</h1><p class="mu">Preenche os teus dados para personalizar a tua experiência.</p><label>Nome</label><input id="on" maxlength="40" autocomplete="off"><label>Idade</label><input id="oa" type="number" inputmode="numeric"><label>Cidade</label><input id="oc" maxlength="60"><div id="oe" class="err"></div><button class="btn" data-a="o1">Continuar</button>`:step===2?`<h1 style="margin-top:30px">Configura o teu ciclo</h1><p class="mu">Precisamos de algumas informações para começar as tuas previsões.</p><label>Primeiro dia da última menstruação</label><input id="ol" type="date" max="${today()}"><label>Quantos dias dura normalmente a menstruação?</label><input id="op" type="number" inputmode="numeric" value="5"><label>Qual é a duração habitual do teu ciclo?</label><input id="oy" type="number" inputmode="numeric" value="28"><button class="chip" id="odk" data-a="odk" style="margin-top:10px">Não sei</button><div class="note" id="odn"></div><div id="oe" class="err"></div><button class="btn" data-a="o2">Guardar e começar</button>`:`<div style="text-align:center;margin-top:90px"><div style="font-size:60px">🌸</div><h1>Está tudo pronto!</h1><p class="mu">Agora vou acompanhar o teu ciclo e ajudar-te a manter tudo organizado.</p><button class="btn" data-a="o3">Começar</button></div>`)+'</div>'}
let OB={};
Object.assign(A,{
o1(){const n=$('#on').value.trim(),a=+$('#oa').value,c=$('#oc').value.trim();if(!n)return $('#oe').textContent='Por favor, indica o teu nome.';if(!Number.isInteger(a)||a<8||a>99)return $('#oe').textContent='Por favor, indica uma idade válida.';if(!c)return $('#oe').textContent='Por favor, indica a tua cidade.';OB={name:n,age:a,city:c};onb(2)},
odk(){const u=OB.unk=!OB.unk;$('#oy').disabled=u;$('#oy').value=28;$('#odk').classList.toggle('on',u);$('#odn').textContent=u?'Vamos começar com 28 dias. A previsão será melhorada à medida que registares novos ciclos.':''},
async o2(){const l=$('#ol').value,pl=+$('#op').value,cl=OB.unk?28:+$('#oy').value;if(!validDate(l)||d2n(l)>d2n(today()))return $('#oe').textContent='Por favor, indica a data em que começou a tua última menstruação.';if(!Number.isInteger(pl)||pl<1||pl>15)return $('#oe').textContent='A menstruação deve durar entre 1 e 15 dias.';if(!Number.isInteger(cl)||cl<15||cl>60)return $('#oe').textContent='O ciclo deve durar entre 15 e 60 dias.';
await dbPut('profile',{id:1,...OB,periodLen:pl,cycleLen:cl,unknown:!!OB.unk,createdAt:Date.now()});await dbPut('cycles',{start:l,end:n2d(d2n(l)+pl-1)<=today()?n2d(d2n(l)+pl-1):null,createdAt:Date.now()});await load();onb(3)},
o3(){$('#ob').hidden=true;enter()}});
function enter(){$('#nav').hidden=false;V='home';render();reminders()}
async function reminders(){const r=S.cfg.rem||{};if(!r.before||!('Notification' in window)||Notification.permission!=='granted')return;if(daysUntilPeriod()===(r.days||2)&&S.cfg.lastN!==today()){S.cfg.lastN=today();await saveCfg();try{const g=await navigator.serviceWorker.getRegistration();if(g)g.showNotification(S.cfg.hideName?'Lembrete':'Fanny App',{body:'Tens um lembrete 🌸',icon:'icon.svg',tag:'ff'})}catch(e){}}}
(async()=>{theme();if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
const wait=new Promise(r=>setTimeout(r,7000));let ok=true;try{await openDB();await load()}catch(e){ok=false}await wait;$('#splash').hidden=true;
if(!ok){$('#main').innerHTML='<div class="pg"><div class="card"><h3>Armazenamento indisponível</h3><p class="mu">Este navegador não permite guardar dados (modo privado?). Abre a app num separador normal.</p></div></div>';return}
if(!S.profile||!S.cycles.length)return onb(1);
if(S.cfg.pin){$('#lock').hidden=false;$('#lbio').hidden=!(S.cfg.bio&&window.PublicKeyCredential);$('#lpin').addEventListener('keydown',e=>{if(e.key==='Enter')A.unlock()})}else enter()})();
